### ISSUE TITLE
Upgrade pydantic version to v2

### ISSUE THREAD

**Issue by MathieuPister** [microsoft/azureml-inference-server#46]
Pydantic v2 is out since june 2023. As the setup.py restricts to pydantic<1.11, we are not able to use the inference server in projects depending of pydantic v2.

**Comment by Northo** [comment]
Any progress on this? We are also affected by this.

**Comment by DannyBruno** [comment]
Apologies for the delayed response. I've gone ahead and created a PR for this migration but we are going to wait until after the New Year to release the changes. I have linked the PRs above.

**Comment by grizzlybearg** [comment]
@DannyBruno Hi, any idea when the next release will be made?
